<a href="https://colab.research.google.com/github/Alex-Casella/msds501_computation/blob/main/01_Exploration_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 01 — Exploration (Google Colab version)

This is the Colab-ready version of the original notebook. Run the **Setup** cell first, then run the notebook top to bottom.

## Setup

pandas is preinstalled in Colab — no installs needed.

---
**Assignment:** each code cell below has been emptied and replaced with `# TODO` hints. Read the markdown above each cell, then write the code yourself. The **Setup** cells (install / upload / imports) already work — run them first.

### Upload data files

When you run the next cell a file picker appears. Select these file(s) from your computer:

- `AlumniGiving_DonationHistory.csv`

In [13]:
from google.colab import files
uploaded = files.upload()  # select the file(s) listed above

import os
print("Uploaded:", sorted(uploaded.keys()))

Saving AlumniGiving_DonationHistory.csv to AlumniGiving_DonationHistory (1).csv
Uploaded: ['AlumniGiving_DonationHistory (1).csv']

# Data Exploration

### Brainstorming
- df.sample(), df.head(), df.tail()
- df.info()
- df.column.value_counts()

In [2]:
import pandas as pd

# Sample, head and tail

In [16]:
# TODO: Load "AlumniGiving_DonationHistory.csv" into a DataFrame named df.
# Hint: pd.read_csv(...)
df = pd.read_csv("AlumniGiving_DonationHistory.csv")
print(df)

                ACCOUNT_ID  NUMBER_OF_DONATIONS  VALUE_OF_DONATIONS  \
0       003o000000pO6zhAAC                    0                 0.0
1       003o000000pOSIxAAO                    1               100.0
2       003o000000pNvhHAAS                    4              1700.0
3       003o000000q0hl1AAA                    0                 0.0
4       003o000000pOZe9AAG                    5               500.0
...                    ...                  ...                 ...
118849  0031J00001Uxe4RQAR                    0                 0.0
118850  0031J00001Wsp1cQAB                    0                 0.0
118851  0031J00001W3RyKQAV                    0                 0.0
118852  0031J00001U449tQAB                    0                 0.0
118853  0031J00001U4HvRQAV                    0                 0.0

                 CITY STATE         ZIP   MI    ALUMNI_TYPE  UG_CLASS_YEAR  \
0         Gainesville    FL  32605-6400  NaN       Graduate           1969
1            Pasadena    CA  91105-1515  NaN       Graduate           1968
2          San Rafael    CA  94901-2478  NaN       Graduate           1964
3         San Antonio    TX  78232-4154    T  Undergraduate           1967
4         Westborough    MA        1581  NaN  Undergraduate           1964
...               ...   ...         ...  ...            ...            ...
118849  San Francisco    CA  94108-3820  NaN       Graduate           2021
118850   Mount Shasta    CA  96067-1194  NaN  Undergraduate           1984
118851     Pleasanton    CA       94588    J       Graduate           2021
118852            NaN   NaN         NaN  NaN       Graduate           2020
118853          Aptos    CA  95003-3172  NaN       Graduate           2020

                       UG_SCHOOL GRAD_DEGREE  GRAD_CLASS_YEAR  \
0                            NaN          MS           1969.0
1                            NaN          JD           1968.0
2                            NaN          JD           1964.0
3              School of Nursing         NaN              NaN
4             School of Business         NaN              NaN
...                          ...         ...              ...
118849                       NaN          MA           2021.0
118850  College of Prof. Studies         NaN              NaN
118851                       NaN          MA           2021.0
118852                       NaN         LLM           2020.0
118853                       NaN         MAT           2020.0

                           GRAD_SCHOOL GENDER MARRIED_TO_ALUM  ROTC  JC
0        College of Arts and Sci (Sci)      M               N     0   0
1                        School of Law      M               N     0   1
2                        School of Law      M               N     0   0
3                                  NaN      F               N     0   0
4                                  NaN      M               N     0   1
...                                ...    ...             ...   ...  ..
118849  College of Arts and Sci (Arts)      F               N     0   0
118850                             NaN      M               N     0   0
118851  College of Arts and Sci (Arts)      F               N     0   0
118852                   School of Law      M               N     0   0
118853             School of Education      F               N     0   0

[118854 rows x 17 columns]

### look at a random sample to gauge the data quality (usually 30 samples is ideal)

In [21]:
# TODO: Look at a random sample of ~5 rows to gauge data quality.
# Hint: DataFrame.sample(n)

df.random = df.sample(n = 5)
print(df.random)

                ACCOUNT_ID  NUMBER_OF_DONATIONS  VALUE_OF_DONATIONS  \
20154   003o000000q0hxQAAQ                    3               250.0
113051  003o000000pONasAAG                    0                 0.0
32331   003o000000pO8xaAAC                    1               500.0
62412   003o000000pNeVMAA0                    0                 0.0
22438   003o000000pO8UxAAK                   10              6000.0

                 CITY STATE         ZIP   MI    ALUMNI_TYPE  UG_CLASS_YEAR  \
20154    Hillsborough    CA  94010-6620  NaN  Undergraduate           2013
113051       Winnetka    IL  60093-4139  NaN       Graduate           2000
32331        Santa Fe    NM  87594-2524  NaN       Graduate           1999
62412         Fremont    CA  94538-4965  NaN  Undergraduate           2006
22438   Crescent City    CA  95531-8447  NaN       Graduate           1964

                             UG_SCHOOL GRAD_DEGREE  GRAD_CLASS_YEAR  \
20154   College of Arts and Sci (Arts)         NaN              NaN
113051                             NaN         MBA           2000.0
32331                              NaN          JD           1999.0
62412         College of Prof. Studies         NaN              NaN
22438                              NaN          JD           1964.0

               GRAD_SCHOOL GENDER MARRIED_TO_ALUM  ROTC  JC
20154                  NaN      M               N     0   0
113051  School of Business      M               N     0   0
32331        School of Law      F               N     0   0
62412                  NaN      F               N     0   0
22438        School of Law      M               N     0   0

### after randomly sampling and noting potential issues, then check the first few rows as well as the final bottom rows since strange errors may occur here such as data being cut off due to slack, etc. (around 15 rows is ideal)

In [23]:
# TODO: Show the first 5 rows.
# Hint: .head()

df.head()

,ACCOUNT_ID,NUMBER_OF_DONATIONS,VALUE_OF_DONATIONS,CITY,STATE,ZIP,MI,ALUMNI_TYPE,UG_CLASS_YEAR,UG_SCHOOL,GRAD_DEGREE,GRAD_CLASS_YEAR,GRAD_SCHOOL,GENDER,MARRIED_TO_ALUM,ROTC,JC
0,003o000000pO6zhAAC,0,0.0,Gainesville,FL,32605-6400,NaN,Graduate,1969,NaN,MS,1969.0,College of Arts and Sci (Sci),M,N,0,0
1,003o000000pOSIxAAO,1,100.0,Pasadena,CA,91105-1515,NaN,Graduate,1968,NaN,JD,1968.0,School of Law,M,N,0,1
2,003o000000pNvhHAAS,4,1700.0,San Rafael,CA,94901-2478,NaN,Graduate,1964,NaN,JD,1964.0,School of Law,M,N,0,0
3,003o000000q0hl1AAA,0,0.0,San Antonio,TX,78232-4154,T,Undergraduate,1967,School of Nursing,NaN,NaN,NaN,F,N,0,0
4,003o000000pOZe9AAG,5,500.0,Westborough,MA,1581,NaN,Undergraduate,1964,School of Business,NaN,NaN,NaN,M,N,0,1

In [24]:
# TODO: Show the last 5 rows.
# Hint: .tail()
df.tail()

,ACCOUNT_ID,NUMBER_OF_DONATIONS,VALUE_OF_DONATIONS,CITY,STATE,ZIP,MI,ALUMNI_TYPE,UG_CLASS_YEAR,UG_SCHOOL,GRAD_DEGREE,GRAD_CLASS_YEAR,GRAD_SCHOOL,GENDER,MARRIED_TO_ALUM,ROTC,JC
118849,0031J00001Uxe4RQAR,0,0.0,San Francisco,CA,94108-3820,NaN,Graduate,2021,NaN,MA,2021.0,College of Arts and Sci (Arts),F,N,0,0
118850,0031J00001Wsp1cQAB,0,0.0,Mount Shasta,CA,96067-1194,NaN,Undergraduate,1984,College of Prof. Studies,NaN,NaN,NaN,M,N,0,0
118851,0031J00001W3RyKQAV,0,0.0,Pleasanton,CA,94588,J,Graduate,2021,NaN,MA,2021.0,College of Arts and Sci (Arts),F,N,0,0
118852,0031J00001U449tQAB,0,0.0,NaN,NaN,NaN,NaN,Graduate,2020,NaN,LLM,2020.0,School of Law,M,N,0,0
118853,0031J00001U4HvRQAV,0,0.0,Aptos,CA,95003-3172,NaN,Graduate,2020,NaN,MAT,2020.0,School of Education,F,N,0,0

## Notes

- binary donor target feature not present (we have to create the target we want to predict i.e., did this person donate at all?)

# Info

### use df.info() to get a general sense of:

- missing data
- size of your data
- primary type of data

### let's look at info

In [25]:
# TODO: Print column names, non-null counts, and dtypes.
# Hint: .info()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118854 entries, 0 to 118853
Data columns (total 17 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ACCOUNT_ID           118854 non-null  object
 1   NUMBER_OF_DONATIONS  118854 non-null  int64
 2   VALUE_OF_DONATIONS   118854 non-null  float64
 3   CITY                 99728 non-null   object
 4   STATE                99728 non-null   object
 5   ZIP                  99728 non-null   object
 6   MI                   12957 non-null   object
 7   ALUMNI_TYPE          118854 non-null  object
 8   UG_CLASS_YEAR        118854 non-null  int64
 9   UG_SCHOOL            70297 non-null   object
 10  GRAD_DEGREE          54423 non-null   object
 11  GRAD_CLASS_YEAR      54422 non-null   float64
 12  GRAD_SCHOOL          54393 non-null   object
 13  GENDER               118854 non-null  object
 14  MARRIED_TO_ALUM      118854 non-null  object
 15  ROTC                 118854 non-null  int64
 16  JC                   118854 non-null  int64
dtypes: float64(2), int64(4), object(11)
memory usage: 15.4+ MB

### what did we learn?

- Missing data: 4 columns have over 50% of their data missing - how will we handle these missing values?
- Size of data: we have about 120_000 rows taking up 15.4MB of space - how can we decrease this size?

### let's see column names - we'll use this later, so I want everyone to see the output

In [27]:
# TODO: List the column names.
# Hint: .columns
df.columns

Index(['ACCOUNT_ID', 'NUMBER_OF_DONATIONS', 'VALUE_OF_DONATIONS', 'CITY',
       'STATE', 'ZIP', 'MI', 'ALUMNI_TYPE', 'UG_CLASS_YEAR', 'UG_SCHOOL',
       'GRAD_DEGREE', 'GRAD_CLASS_YEAR', 'GRAD_SCHOOL', 'GENDER',
       'MARRIED_TO_ALUM', 'ROTC', 'JC'],
      dtype='object')

# Value counts

### df.column.value_counts() is probably the most important method you have when exploring data

In [28]:
# TODO: Count how often each value appears in the CITY column.
# Hint: use .value_counts() on df["CITY"]
df['CITY'].value_counts()

CITY
San Francisco     13763
San Jose           3201
Oakland            2523
Sacramento         1869
Santa Rosa         1247
                  ...
Scottsboro            1
Nobleboro             1
Kewaunee              1
Flowery Branch        1
Alma                  1
Name: count, Length: 4515, dtype: int64

### make this alphabetical order

In [34]:
# TODO: Print the first 20 unique CITY values in alphabetical order
#       (handy for spotting spelling / capitalization inconsistencies).
# Hint: combine sorted(), set(), and .value_counts().index
sorted(set(df['CITY'].value_counts().index))[:20]

['APO',
 'Abbeville',
 'Aberdeen',
 'Abingdon',
 'Abington',
 'Abiquiu',
 'Absecon',
 'Acampo',
 'Accident',
 'Accokeek',
 'Acme',
 'Acton',
 'Acworth',
 'Ada',
 'Addison',
 'Adel',
 'Adelanto',
 'Adelphi',
 'Adrian',
 'Afton']

### let's do a for loop of value counts and take some notes about cardinality and the patterns we see

In [11]:
# TODO: List the column names.
# Hint: .columns

## what do we think?
- what are the likely suspects to drop from further analysis? Why?

## Some things to think about:

- Is ACCOUNT_ID a useless column due to high cardinality?
- Is MI a useless column due to what it represents and the number of missing values?